version: "3.3"
services:
  omnirule_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgresql-local
    volumes:
      - "./postgres.sock:/var/run/postgres/postgres.sock"
      - "./postgres:/var/lib/postgresql/data"
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=my_awesome_email@email.com
      - PGADMIN_DEFAULT_PASSWORD=does_not_matter
    depends_on:
      - omnirule_db
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - 6379:6379