version: "3.3"
services:
  omnirule_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgresql-local
    volumes:
      - "./postgres.sock:/var/run/postgres/postgres.sock"
      - "./postgres:/var/lib/postgresql/data"
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=my_awesome_email@email.com
      - PGADMIN_DEFAULT_PASSWORD=does_not_matter
    depends_on:
      - omnirule_db
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - 6379:6379
  omni-cloud1:
    image: omni-cloud
    container_name: omni-cloud-1
    depends_on:
      - omnirule_db
    #ports:
    #  - 3001:3000
  omni-cloud2:
    image: omni-cloud
    container_name: omni-cloud-2
    depends_on:
      - omnirule_db
    #ports:
    #  - 3002:3000
  omni-cloud3:
    image: omni-cloud
    container_name: omni-cloud-3
    depends_on:
      - omnirule_db
    #ports:
    #  - 3003:3000
  omni-cloud4:
    image: omni-cloud
    container_name: omni-cloud-4
    depends_on:
      - omnirule_db
    #ports:
    #  - 3004:3000
  omni-cloud5:
    image: omni-cloud
    container_name: omni-cloud-5
    depends_on:
      - omnirule_db
    #ports:
    #  - 3005:3000
  nginx:
    image: load-balance-nginx
    container_name: nginx-omni
    depends_on:
      - omnirule_db
      - redis
    ports:
      - 8100:80
